package capaPresentacion;

import capaDatos.accesoDatos;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

public class frmRegistro extends javax.swing.JFrame {
    int xMouse;int yMouse;
    accesoDatos conn = new accesoDatos();
    public frmRegistro() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new JPanel();
        btnExit = new JPanel();
        lblBtnExit = new JLabel();
        lblIngreso = new JLabel();
        lblDocumento = new JLabel();
        lblNombre = new JLabel();
        lblEmail = new JLabel();
        lblTelefono = new JLabel();
        txtDocumento = new JTextField();
        txtNombre = new JTextField();
        txtEmail = new JTextField();
        txtTelefono = new JTextField();
        lblCamara = new JLabel();
        btnTomarFoto = new JPanel();
        lblTomarFoto = new JLabel();
        btnRegistrarse = new JPanel();
        lblRegistrarse = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlPrincipal.setBackground(new Color(230, 230, 250));
        pnlPrincipal.setPreferredSize(new Dimension(540, 343));
        pnlPrincipal.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                pnlPrincipalMouseDragged(evt);
            }
        });
        pnlPrincipal.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                pnlPrincipalMousePressed(evt);
            }
        });
        pnlPrincipal.setLayout(new AbsoluteLayout());

        btnExit.setBackground(new Color(230, 230, 250));

        lblBtnExit.setBackground(new Color(230, 230, 250));
        lblBtnExit.setFont(new Font("Segoe UI", 1, 16)); // NOI18N
        lblBtnExit.setHorizontalAlignment(SwingConstants.CENTER);
        lblBtnExit.setText("X");
        lblBtnExit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                lblBtnExitMouseClicked(evt);
            }
            public void mouseEntered(MouseEvent evt) {
                lblBtnExitMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                lblBtnExitMouseExited(evt);
            }
        });

        GroupLayout btnExitLayout = new GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(btnExitLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBtnExit, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(btnExitLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBtnExit, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        );

        pnlPrincipal.add(btnExit, new AbsoluteConstraints(510, 0, 30, 30));

        lblIngreso.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lblIngreso.setHorizontalAlignment(SwingConstants.LEFT);
        lblIngreso.setText("Registro");
        pnlPrincipal.add(lblIngreso, new AbsoluteConstraints(30, 0, 130, -1));

        lblDocumento.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblDocumento.setText("Documento");
        lblDocumento.setToolTipText("");
        pnlPrincipal.add(lblDocumento, new AbsoluteConstraints(30, 70, -1, -1));

        lblNombre.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombres Completos");
        lblNombre.setToolTipText("");
        pnlPrincipal.add(lblNombre, new AbsoluteConstraints(30, 100, -1, -1));

        lblEmail.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setToolTipText("");
        pnlPrincipal.add(lblEmail, new AbsoluteConstraints(30, 130, -1, -1));

        lblTelefono.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefono.setText("Telefono");
        lblTelefono.setToolTipText("");
        pnlPrincipal.add(lblTelefono, new AbsoluteConstraints(30, 160, -1, -1));
        pnlPrincipal.add(txtDocumento, new AbsoluteConstraints(200, 70, 120, -1));
        pnlPrincipal.add(txtNombre, new AbsoluteConstraints(200, 100, 120, -1));
        pnlPrincipal.add(txtEmail, new AbsoluteConstraints(200, 130, 120, -1));
        pnlPrincipal.add(txtTelefono, new AbsoluteConstraints(200, 160, 120, -1));

        lblCamara.setIcon(new ImageIcon(getClass().getResource("/img/camara-web.png"))); // NOI18N
        pnlPrincipal.add(lblCamara, new AbsoluteConstraints(370, 60, -1, -1));

        btnTomarFoto.setBackground(new Color(138, 138, 194));

        lblTomarFoto.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblTomarFoto.setHorizontalAlignment(SwingConstants.CENTER);
        lblTomarFoto.setText("TOMAR FOTO");
        lblTomarFoto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblTomarFoto.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                lblTomarFotoMouseClicked(evt);
            }
            public void mouseEntered(MouseEvent evt) {
                lblTomarFotoMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                lblTomarFotoMouseExited(evt);
            }
        });

        GroupLayout btnTomarFotoLayout = new GroupLayout(btnTomarFoto);
        btnTomarFoto.setLayout(btnTomarFotoLayout);
        btnTomarFotoLayout.setHorizontalGroup(btnTomarFotoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(btnTomarFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTomarFoto, GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTomarFotoLayout.setVerticalGroup(btnTomarFotoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, btnTomarFotoLayout.createSequentialGroup()
                .addComponent(lblTomarFoto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPrincipal.add(btnTomarFoto, new AbsoluteConstraints(350, 190, -1, 30));

        btnRegistrarse.setBackground(new Color(138, 138, 194));

        lblRegistrarse.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistrarse.setHorizontalAlignment(SwingConstants.CENTER);
        lblRegistrarse.setText("REGISTRARSE");
        lblRegistrarse.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblRegistrarse.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });

        GroupLayout btnRegistrarseLayout = new GroupLayout(btnRegistrarse);
        btnRegistrarse.setLayout(btnRegistrarseLayout);
        btnRegistrarseLayout.setHorizontalGroup(btnRegistrarseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, btnRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarse, GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegistrarseLayout.setVerticalGroup(btnRegistrarseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarseLayout.createSequentialGroup()
                .addComponent(lblRegistrarse, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPrincipal.add(btnRegistrarse, new AbsoluteConstraints(210, 310, 150, 30));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, GroupLayout.PREFERRED_SIZE, 365, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnExitMouseClicked(MouseEvent evt) {//GEN-FIRST:event_lblBtnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblBtnExitMouseClicked

    private void lblBtnExitMouseEntered(MouseEvent evt) {//GEN-FIRST:event_lblBtnExitMouseEntered
        btnExit.setBackground(Color.red);
    }//GEN-LAST:event_lblBtnExitMouseEntered

    private void lblBtnExitMouseExited(MouseEvent evt) {//GEN-FIRST:event_lblBtnExitMouseExited
        btnExit.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblBtnExitMouseExited

    private void pnlPrincipalMouseDragged(MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMouseDragged
        int x = evt.getXOnScreen();int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_pnlPrincipalMouseDragged

    private void pnlPrincipalMousePressed(MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlPrincipalMousePressed

    private void lblRegistrarseMouseClicked(MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        
        

    }//GEN-LAST:event_lblRegistrarseMouseClicked

    private void lblRegistrarseMouseEntered(MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
        btnRegistrarse.setBackground(new Color(150,150,213));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseExited(MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        btnRegistrarse.setBackground(new Color(138,138,194));
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void lblTomarFotoMouseClicked(MouseEvent evt) {//GEN-FIRST:event_lblTomarFotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTomarFotoMouseClicked

    private void lblTomarFotoMouseEntered(MouseEvent evt) {//GEN-FIRST:event_lblTomarFotoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTomarFotoMouseEntered

    private void lblTomarFotoMouseExited(MouseEvent evt) {//GEN-FIRST:event_lblTomarFotoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTomarFotoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel btnExit;
    private JPanel btnRegistrarse;
    private JPanel btnTomarFoto;
    private JLabel lblBtnExit;
    private JLabel lblCamara;
    private JLabel lblDocumento;
    private JLabel lblEmail;
    private JLabel lblIngreso;
    private JLabel lblNombre;
    private JLabel lblRegistrarse;
    private JLabel lblTelefono;
    private JLabel lblTomarFoto;
    private JPanel pnlPrincipal;
    private JTextField txtDocumento;
    private JTextField txtEmail;
    private JTextField txtNombre;
    private JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
